# DO NOT EDIT THIS FILE
setenv load_addr "0x43100000"
setenv overlay_error "false"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "on"

echo "Boot script loaded from ${devtype} ${devnum}"

if test -e ${devtype} ${devnum} ${prefix}orangepiEnv.txt; then
        load ${devtype} ${devnum} ${load_addr} ${prefix}orangepiEnv.txt
        env import -t ${load_addr} ${filesize}
fi

# --- EDK2 chainload (skip if /boot/skip_edk2 exists) ---
if test -e ${devtype} ${devnum} ${prefix}skip_edk2; then
        echo "*** /boot/skip_edk2 flag present - SKIPPING EDK2, booting stock Linux ***"
else
        echo "*** Chainloading EDK2 UEFI firmware ***"
        echo "*** ( To skip next boot: touch /boot/skip_edk2 from Linux )      ***"
        load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}ORANGEPI4PRO_EFI.uimg
        load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
        fdt addr ${fdt_addr_r}
        fdt resize 65536
        setenv bootargs "earlycon earlyprintk=sunxi-uart,0x02500000 console=ttyS0,115200"
        bootm ${kernel_addr_r} - ${fdt_addr_r}
        echo "EDK2 returned - falling through to Linux"
fi
# --- end EDK2 chainload ---

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlyprintk=sunxi-uart,0x02500000 initcall_debug=0 ${consoleargs}"; fi

part uuid ${devtype} ${devnum}:1 partuuid
if test -z "${rootdev}"; then rootdev=PARTUUID="${partuuid}"; fi
setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} clk_ignore_unused swiotlb=65536 ${extraargs} ${extraboardargs}"
if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi

load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}uImage
load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
bootm ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
